### ISSUE TITLE
Update to Build21-RC1

### ISSUE THREAD

**Issue by scx** [flathub/org.widelands.Widelands#19]
## TO-DO

- [x] Switch to the `build21-rc1` tag
- [x] Handle the new version string
- [x] Update modules
  - [x] Update `lua`
  - [x] Update `glew`
- [x] Test on various GPUs
  - [x] Test on Mesa driver (Intel `i965`)
   - [x] Test on proprietary driver (NVIDIA)
- [x] Perform long run tests

I am going to release it today in the `beta` channel. PR is on the way.

**Comment by scx** [comment]
Because **Freedesktop 19.08** switched from **Mesa 20.0** to **Mesa 20.1** just a few days ago, I decided to do test it a little bit longer.

Because `iris` is no longer the default driver, the problem with crashes on older distributions has been temporarily resolved.
https://github.com/widelands/widelands/issues/3937

Other issues:
https://github.com/widelands/widelands/issues/3979

PR:
https://github.com/flathub/org.widelands.Widelands/pull/20

Stand-alone package:
https://github.com/scx/widelands-flatpak/releases/tag/v21-rc1+20200713
